-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2024-05-02 13:18:26.964

-- tables
-- Table: ALUMNO
CREATE TABLE ALUMNO (
    LU int  NOT NULL,
    nombre varchar(40)  NOT NULL,
    provincia varchar(30)  NOT NULL,
    CONSTRAINT PK_ALUMNO PRIMARY KEY (LU)
);

-- Table: CURSO
CREATE TABLE CURSO (
    cod char(4)  NOT NULL,
    descripcion varchar(40)  NOT NULL,
    tipo char(1)  NOT NULL,
    INSCRIPTO_CURSO_cod char(4)  NOT NULL,
    INSCRIPTO_ALUMNO_LU int  NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (cod)
);

-- Table: INSCRIPTO
CREATE TABLE INSCRIPTO (
    CURSO_cod char(4)  NOT NULL,
    ALUMNO_LU int  NOT NULL,
    CONSTRAINT PK_INSCRIPTO PRIMARY KEY (CURSO_cod,ALUMNO_LU)
);

-- foreign keys
-- Reference: CURSO_INSCRIPTO (table: CURSO)
ALTER TABLE CURSO ADD CONSTRAINT CURSO_INSCRIPTO
    FOREIGN KEY (INSCRIPTO_CURSO_cod, INSCRIPTO_ALUMNO_LU)
    REFERENCES INSCRIPTO (CURSO_cod, ALUMNO_LU)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: INSCRIPTO_ALUMNO (table: INSCRIPTO)
ALTER TABLE INSCRIPTO ADD CONSTRAINT INSCRIPTO_ALUMNO
    FOREIGN KEY (ALUMNO_LU)
    REFERENCES ALUMNO (LU)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: INSCRIPTO_CURSO (table: INSCRIPTO)
ALTER TABLE INSCRIPTO ADD CONSTRAINT INSCRIPTO_CURSO
    FOREIGN KEY (CURSO_cod)
    REFERENCES CURSO (cod)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

