-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2024-05-02 13:30:40.996

-- tables
-- Table: EQUIPO
CREATE TABLE EQUIPO (
    nro_equipo int  NOT NULL,
    descripcion varchar(50)  NOT NULL,
    CONSTRAINT PK_EQUIPO PRIMARY KEY (nro_equipo)
);

-- Table: GRABACION
CREATE TABLE GRABACION (
    nro_grabacion int  NOT NULL,
    casa_discografica varchar(50)  NOT NULL,
    fecha_grabacion date  NOT NULL,
    tipo char(1)  NOT NULL,
    CONSTRAINT PK_GRABACION PRIMARY KEY (nro_grabacion)
);

-- Table: GRABACION_COMERCIAL
CREATE TABLE GRABACION_COMERCIAL (
    GRABACION_nro_grabacion int  NOT NULL,
    EQUIPO_nro_equipo int  NOT NULL,
    CONSTRAINT PK_GRABACION_COMERCIAL PRIMARY KEY (GRABACION_nro_grabacion)
);

-- Table: GRABACION_NO_PROPIA
CREATE TABLE GRABACION_NO_PROPIA (
    duracion int  NOT NULL,
    GRABACION_nro_grabacion int  NOT NULL,
    CONSTRAINT PK_GRABACION_NO_PROPIA PRIMARY KEY (GRABACION_nro_grabacion)
);

-- foreign keys
-- Reference: GRABACION_COMERCIAL_EQUIPO (table: GRABACION_COMERCIAL)
ALTER TABLE GRABACION_COMERCIAL ADD CONSTRAINT GRABACION_COMERCIAL_EQUIPO
    FOREIGN KEY (EQUIPO_nro_equipo)
    REFERENCES EQUIPO (nro_equipo)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: GRABACION_COMERCIAL_GRABACION (table: GRABACION_COMERCIAL)
ALTER TABLE GRABACION_COMERCIAL ADD CONSTRAINT GRABACION_COMERCIAL_GRABACION
    FOREIGN KEY (GRABACION_nro_grabacion)
    REFERENCES GRABACION (nro_grabacion)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: GRABACION_NO_PROPIA_GRABACION (table: GRABACION_NO_PROPIA)
ALTER TABLE GRABACION_NO_PROPIA ADD CONSTRAINT GRABACION_NO_PROPIA_GRABACION
    FOREIGN KEY (GRABACION_nro_grabacion)
    REFERENCES GRABACION (nro_grabacion)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

